//* Booleans and Comparison Operator

// Booleans will return True or False Only

let num1 = 8;
let num2 = 10; 

console.log(num1>num2); //false bcoz 8 > 10 
console.log(num1<num2); //true bcoz 8 < 10 

//* Comparision Operators
// == -> equal to -> 8 == 8 -> True
let x  = 8;
console.log(x==9); // false -> 8==9 -> False
// === 

let a  = "8";
console.log(a===8); //False bcoz === will check Datatype and value also
console.log(a==="8"); //True bcoz === will check Datatype and value also -> "8"==="8"

// !=

let b = 9;
console.log(b!=9); //False Bcoz b is equal to 9 
console.log(b!=8); //True Bcoz b is not equal to 9 

// !== // It will check value and datatype also

let d = 9;
console.log(b !== "9"); //True Bcoz values are same but datatype is diffrent 
console.log(b !== 9); //false Bcoz value or datatype are same and we want not equal to 9

// >
let e = 10;
console.log(e > 5); // True Bcoz 10 > 5 

// <
let f = 10;
console.log(e < 5); // false Bcoz 10 < 5 

// >=

let g = 18;
console.log(g >= 19); //false bcoz 18 >= 19
console.log(g >= 18); //true bcoz 18 >= 18 means 18 == 18
// <=
