//* elseif in Javasript

// if
// else if
// else if
// else if
// else

let tempInDegree = 43;

if(tempInDegree < 0){
    console.log("Extremely Cold Outside");
}
else if(tempInDegree < 15){
    console.log("It is Cold Outside");
}
else if(tempInDegree < 25){
    console.log("Whather is okay");
}
else if(tempInDegree < 35){
    console.log("Let's go for Swim");
}
else if(tempInDegree < 45){
    console.log("Turn on AC");
}
else{
    console.log("Too hot");
}