//* Switch Statement in Javascript

// print Days by number

let day = 8;

switch(day){
    case 1:
        console.log("Sunday");
        break;
    case 2:
        console.log("Monday");
        break;
    case 3:
        console.log("Tuesday");
        break;
    case 4:
        console.log("Wednesday");
        break;
    case 5:
        console.log("Thirstday");
        break;
    case 6:
        console.log("Firday");
        break;
    case 7:
        console.log("Saturnday");
        break;

    default:
        console.log("Invalid Input Plz enter a number between 1 to 7");
        
    
}